name: WSL + GCC

defaults:
    run:
        shell: wsl-bash {0}

on:
  push:
    branches: [ master, ci_wsl ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: "Build & Test"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:    ["windows-latest"]
        gcc:   ["8", "10"]
        py:    ["3.7"]
        cmake: ["3.18.x"]
        mpi:   ["OFF"]
    steps:
      - name: Setup WSL
        uses: Vampire/setup-wsl@v1.0.1
        with:
          distribution: 'Ubuntu-20.04'
      - name: whatterm
        run: echo $TERM
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.4
        with:
          cmake-version: ${{ matrix.cmake }}
      - name: whatcmake
        run: which cmake